export const currencies = [
  { label: "USD - United States Dollar", value: "USD" },
  { label: "EUR - Euro", value: "EUR" },
  { label: "JPY - Japanese Yen", value: "JPY" },
  { label: "GBP - British Pound Sterling", value: "GBP" },
  { label: "AUD - Australian Dollar", value: "AUD" },
  { label: "CAD - Canadian Dollar", value: "CAD" },
  { label: "CHF - Swiss Franc", value: "CHF" },
  { label: "CNY - Chinese Yuan Renminbi", value: "CNY" },
  { label: "INR - Indian Rupee", value: "INR" },
  { label: "RUB - Russian Ruble", value: "RUB" },
  { label: "BRL - Brazilian Real", value: "BRL" },
  { label: "ZAR - South African Rand", value: "ZAR" },
  { label: "MXN - Mexican Peso", value: "MXN" },
  { label: "SGD - Singapore Dollar", value: "SGD" },
  { label: "NZD - New Zealand Dollar", value: "NZD" },
  { label: "HKD - Hong Kong Dollar", value: "HKD" },
  { label: "ALL - Albanian Lek", value: "ALL" },
  { label: "AFN - Afghan Afghani", value: "AFN" },
  { label: "ARS - Argentine Peso", value: "ARS" },
  { label: "AWG - Aruban Florin", value: "AWG" },
  { label: "AZN - Azerbaijani Manat", value: "AZN" },
  { label: "BSD - Bahamian Dollar", value: "BSD" },
  { label: "BHD - Bahraini Dinar", value: "BHD" },
  { label: "BDT - Bangladeshi Taka", value: "BDT" },
  { label: "BBD - Barbadian Dollar", value: "BBD" },
  { label: "BYN - Belarusian Ruble", value: "BYN" },
  { label: "BZD - Belize Dollar", value: "BZD" },
  { label: "BMD - Bermudian Dollar", value: "BMD" },
  { label: "BTN - Bhutanese Ngultrum", value: "BTN" },
  { label: "BOB - Bolivian Boliviano", value: "BOB" },
  { label: "BAM - Bosnia and Herzegovina Convertible Mark", value: "BAM" },
  { label: "BWP - Botswana Pula", value: "BWP" },
  { label: "BND - Brunei Dollar", value: "BND" },
  { label: "BGN - Bulgarian Lev", value: "BGN" },
  { label: "KHR - Cambodian Riel", value: "KHR" },
  { label: "CLP - Chilean Peso", value: "CLP" },
  { label: "COP - Colombian Peso", value: "COP" },
  { label: "CRC - Costa Rican Colón", value: "CRC" },
  { label: "HRK - Croatian Kuna", value: "HRK" },
  { label: "CUP - Cuban Peso", value: "CUP" },
  { label: "CZK - Czech Koruna", value: "CZK" },
  { label: "DKK - Danish Krone", value: "DKK" },
  { label: "DOP - Dominican Peso", value: "DOP" },
  { label: "XCD - East Caribbean Dollar", value: "XCD" },
  { label: "EGP - Egyptian Pound", value: "EGP" },
  { label: "ERN - Eritrean Nakfa", value: "ERN" },
  { label: "ETB - Ethiopian Birr", value: "ETB" },
  { label: "FJD - Fijian Dollar", value: "FJD" },
  { label: "GMD - Gambian Dalasi", value: "GMD" },
  { label: "GEL - Georgian Lari", value: "GEL" },
  { label: "GHS - Ghanaian Cedi", value: "GHS" },
  { label: "GIP - Gibraltar Pound", value: "GIP" },
  { label: "GTQ - Guatemalan Quetzal", value: "GTQ" },
  { label: "GNF - Guinean Franc", value: "GNF" },
  { label: "GYD - Guyanese Dollar", value: "GYD" },
  { label: "HUF - Hungarian Forint", value: "HUF" },
  { label: "ISK - Icelandic Króna", value: "ISK" },
  { label: "IDR - Indonesian Rupiah", value: "IDR" },
  { label: "IQD - Iraqi Dinar", value: "IQD" },
  { label: "IRR - Iranian Rial", value: "IRR" },
  { label: "ILS - Israeli New Shekel", value: "ILS" },
  { label: "JMD - Jamaican Dollar", value: "JMD" },
  { label: "JOD - Jordanian Dinar", value: "JOD" },
  { label: "KZT - Kazakhstani Tenge", value: "KZT" },
  { label: "KES - Kenyan Shilling", value: "KES" },
  { label: "KWD - Kuwaiti Dinar", value: "KWD" },
  { label: "KGS - Kyrgyzstani Som", value: "KGS" },
  { label: "LAK - Laotian Kip", value: "LAK" },
  { label: "LBP - Lebanese Pound", value: "LBP" },
  { label: "LRD - Liberian Dollar", value: "LRD" },
  { label: "LYD - Libyan Dinar", value: "LYD" },
  { label: "MOP - Macanese Pataca", value: "MOP" },
  { label: "MGA - Malagasy Ariary", value: "MGA" },
  { label: "MYR - Malaysian Ringgit", value: "MYR" },
  { label: "MVR - Maldivian Rufiyaa", value: "MVR" },
  { label: "MUR - Mauritian Rupee", value: "MUR" },
  { label: "MDL - Moldovan Leu", value: "MDL" },
  { label: "MNT - Mongolian Tögrög", value: "MNT" },
  { label: "MAD - Moroccan Dirham", value: "MAD" },
  { label: "MZN - Mozambican Metical", value: "MZN" },
  { label: "MMK - Myanmar Kyat", value: "MMK" },
  { label: "NAD - Namibian Dollar", value: "NAD" },
  { label: "NPR - Nepalese Rupee", value: "NPR" },
  { label: "ANG - Netherlands Antillean Guilder", value: "ANG" },
  { label: "TWD - New Taiwan Dollar", value: "TWD" },
  { label: "NIO - Nicaraguan Córdoba", value: "NIO" },
  { label: "NGN - Nigerian Naira", value: "NGN" },
  { label: "KPW - North Korean Won", value: "KPW" },
  { label: "NOK - Norwegian Krone", value: "NOK" },
  { label: "OMR - Omani Rial", value: "OMR" },
  { label: "PKR - Pakistani Rupee", value: "PKR" },
  { label: "PAB - Panamanian Balboa", value: "PAB" },
  { label: "PGK - Papua New Guinean Kina", value: "PGK" },
  { label: "PYG - Paraguayan Guarani", value: "PYG" },
  { label: "PEN - Peruvian Sol", value: "PEN" },
  { label: "PHP - Philippine Peso", value: "PHP" },
  { label: "PLN - Polish Złoty", value: "PLN" },
  { label: "QAR - Qatari Riyal", value: "QAR" },
  { label: "RON - Romanian Leu", value: "RON" },
  { label: "RWF - Rwandan Franc", value: "RWF" },
  { label: "SAR - Saudi Riyal", value: "SAR" },
  { label: "RSD - Serbian Dinar", value: "RSD" },
  { label: "SCR - Seychellois Rupee", value: "SCR" },
  { label: "SLL - Sierra Leonean Leone", value: "SLL" },
  { label: "SBD - Solomon Islands Dollar", value: "SBD" },
  { label: "SOS - Somali Shilling", value: "SOS" },
  { label: "KRW - South Korean Won", value: "KRW" },
  { label: "LKR - Sri Lankan Rupee", value: "LKR" },
  { label: "SDG - Sudanese Pound", value: "SDG" },
  { label: "SEK - Swedish Krona", value: "SEK" },
  { label: "SYP - Syrian Pound", value: "SYP" },
  { label: "TJS - Tajikistani Somoni", value: "TJS" },
  { label: "TZS - Tanzanian Shilling", value: "TZS" },
  { label: "THB - Thai Baht", value: "THB" },
  { label: "TOP - Tongan Paʻanga", value: "TOP" },
  { label: "TTD - Trinidad and Tobago Dollar", value: "TTD" },
  { label: "TND - Tunisian Dinar", value: "TND" },
  { label: "TRY - Turkish Lira", value: "TRY" },
  { label: "TMT - Turkmenistan Manat", value: "TMT" },
  { label: "UGX - Ugandan Shilling", value: "UGX" },
  { label: "UAH - Ukrainian Hryvnia", value: "UAH" },
  { label: "AED - United Arab Emirates Dirham", value: "AED" },
  { label: "UYU - Uruguayan Peso", value: "UYU" },
  { label: "UZS - Uzbekistani Soʻm", value: "UZS" },
  { label: "VUV - Vanuatu Vatu", value: "VUV" },
  { label: "VES - Venezuelan Bolívar Soberano", value: "VES" },
  { label: "VND - Vietnamese Đồng", value: "VND" },
  { label: "YER - Yemeni Rial", value: "YER" },
  { label: "ZMW - Zambian Kwacha", value: "ZMW" },
];
