export const languages = [
  { code: "af", label: "Afrikaans", name: "Afrikaans" },
  { code: "sq", label: "Albanian", name: "Shqip" },
  { code: "am", label: "Amharic", name: "አማርኛ" },
  { code: "ar", label: "Arabic", name: "العربية" },
  { code: "hy", label: "Armenian", name: "Հայերեն" },
  { code: "az", label: "Azerbaijani", name: "Azərbaycan" },
  { code: "eu", label: "Basque", name: "Euskara" },
  { code: "be", label: "Belarusian", name: "Беларуская" },
  { code: "bn", label: "Bengali", name: "বাংলা" },
  { code: "bs", label: "Bosnian", name: "Bosanski" },
  { code: "bg", label: "Bulgarian", name: "Български" },
  { code: "ca", label: "Catalan", name: "Català" },
  { code: "ceb", label: "Cebuano", name: "Cebuano" },
  { code: "zh", label: "Chinese (Simplified)", name: "简体中文" },
  { code: "zh-TW", label: "Chinese (Traditional)", name: "繁體中文" },
  { code: "co", label: "Corsican", name: "Corsu" },
  { code: "hr", label: "Croatian", name: "Hrvatski" },
  { code: "cs", label: "Czech", name: "Čeština" },
  { code: "da", label: "Danish", name: "Dansk" },
  { code: "nl", label: "Dutch", name: "Nederlands" },
  { code: "en", label: "English", name: "English" },
  { code: "eo", label: "Esperanto", name: "Esperanto" },
  { code: "et", label: "Estonian", name: "Eesti" },
  { code: "fi", label: "Finnish", name: "Suomi" },
  { code: "fr", label: "French", name: "Français" },
  { code: "fy", label: "Frisian", name: "Frysk" },
  { code: "gl", label: "Galician", name: "Galego" },
  { code: "ka", label: "Georgian", name: "ქართული" },
  { code: "de", label: "German", name: "Deutsch" },
  { code: "el", label: "Greek", name: "Ελληνικά" },
  { code: "gu", label: "Gujarati", name: "ગુજરાતી" },
  { code: "ht", label: "Haitian Creole", name: "Kreyòl ayisyen" },
  { code: "ha", label: "Hausa", name: "Hausa" },
  { code: "haw", label: "Hawaiian", name: "Ōlelo Hawaiʻi" },
  { code: "he", label: "Hebrew", name: "עברית" },
  { code: "hi", label: "Hindi", name: "हिन्दी" },
  { code: "hmn", label: "Hmong", name: "Hmoob" },
  { code: "hu", label: "Hungarian", name: "Magyar" },
  { code: "is", label: "Icelandic", name: "Íslenska" },
  { code: "ig", label: "Igbo", name: "Igbo" },
  { code: "id", label: "Indonesian", name: "Bahasa Indonesia" },
  { code: "ga", label: "Irish", name: "Gaeilge" },
  { code: "it", label: "Italian", name: "Italiano" },
  { code: "ja", label: "Japanese", name: "日本語" },
  { code: "jw", label: "Javanese", name: "Jawa" },
  { code: "kn", label: "Kannada", name: "ಕನ್ನಡ" },
  { code: "kk", label: "Kazakh", name: "Қазақ" },
  { code: "km", label: "Khmer", name: "ខ្មែរ" },
  { code: "ko", label: "Korean", name: "한국어" },
  { code: "ku", label: "Kurdish", name: "Kurdî" },
  { code: "ky", label: "Kyrgyz", name: "Кыргызча" },
  { code: "lo", label: "Lao", name: "ລາວ" },
  { code: "la", label: "Latin", name: "Latina" },
  { code: "lv", label: "Latvian", name: "Latviešu" },
  { code: "lt", label: "Lithuanian", name: "Lietuvių" },
  { code: "lb", label: "Luxembourgish", name: "Lëtzebuergesch" },
  { code: "mk", label: "Macedonian", name: "Македонски" },
  { code: "mg", label: "Malagasy", name: "Malagasy" },
  { code: "ms", label: "Malay", name: "Bahasa Melayu" },
  { code: "ml", label: "Malayalam", name: "മലയാളം" },
  { code: "mt", label: "Maltese", name: "Malti" },
  { code: "mi", label: "Maori", name: "Māori" },
  { code: "mr", label: "Marathi", name: "मराठी" },
  { code: "mn", label: "Mongolian", name: "Монгол" },
  { code: "my", label: "Myanmar (Burmese)", name: "မြန်မာ" },
  { code: "ne", label: "Nepali", name: "नेपाली" },
  { code: "no", label: "Norwegian", name: "Norsk" },
  { code: "ny", label: "Nyanja (Chichewa)", name: "ChiChewa" },
  { code: "ps", label: "Pashto", name: "پښتو" },
  { code: "fa", label: "Persian", name: "فارسی" },
  { code: "pl", label: "Polish", name: "Polski" },
  { code: "pt", label: "Portuguese", name: "Português" },
  { code: "pa", label: "Punjabi", name: "ਪੰਜਾਬੀ" },
  { code: "ro", label: "Romanian", name: "Română" },
  { code: "ru", label: "Russian", name: "Русский" },
  { code: "sm", label: "Samoan", name: "Gagana Samoa" },
  { code: "gd", label: "Scots Gaelic", name: "Gàidhlig" },
  { code: "sr", label: "Serbian", name: "Српски" },
  { code: "st", label: "Sesotho", name: "Sesotho" },
  { code: "sn", label: "Shona", name: "Chishona" },
  { code: "sd", label: "Sindhi", name: "سنڌي" },
  { code: "si", label: "Sinhala (Sinhalese)", name: "සිංහල" },
  { code: "sk", label: "Slovak", name: "Slovenčina" },
  { code: "sl", label: "Slovenian", name: "Slovenščina" },
  { code: "so", label: "Somali", name: "Soomaali" },
  { code: "es", label: "Spanish", name: "Español" },
  { code: "su", label: "Sundanese", name: "Basa Sunda" },
  { code: "sw", label: "Swahili", name: "Kiswahili" },
  { code: "sv", label: "Swedish", name: "Svenska" },
  { code: "tl", label: "Tagalog (Filipino)", name: "Filipino" },
  { code: "tg", label: "Tajik", name: "Тоҷикӣ" },
  { code: "ta", label: "Tamil", name: "தமிழ்" },
  { code: "te", label: "Telugu", name: "తెలుగు" },
  { code: "th", label: "Thai", name: "ไทย" },
  { code: "tr", label: "Turkish", name: "Türkçe" },
  { code: "uk", label: "Ukrainian", name: "Українська" },
  { code: "ur", label: "Urdu", name: "اردو" },
  { code: "uz", label: "Uzbek", name: "Oʻzbek" },
  { code: "vi", label: "Vietnamese", name: "Tiếng Việt" },
  { code: "cy", label: "Welsh", name: "Cymraeg" },
  { code: "xh", label: "Xhosa", name: "isiXhosa" },
  { code: "yi", label: "Yiddish", name: "ייִדיש" },
  { code: "yo", label: "Yoruba", name: "Yorùbá" },
  { code: "zu", label: "Zulu", name: "isiZulu" },
];
