# Generated by Django 5.2.8 on 2025-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                    ("TRANSFER", "Transfer"),
                ],
                max_length=8,
            ),
        ),
    ]
